# Generated by Django 4.1.3 on 2022-11-28 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0002_issue_assignee_issue_reporter_project_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="reporter",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reporter",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
