# Generated by Django 4.1.3 on 2022-12-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_alter_project_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
