# Generated by Django 4.1.3 on 2022-12-03 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tag", "0001_initial"),
        ("project", "0005_alter_project_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issues",
                to="tag.tag",
            ),
        ),
    ]
