# Generated by Django 4.1.3 on 2022-12-05 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tag", "0001_initial"),
        ("project", "0006_issue_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tagged_issues",
                to="tag.tag",
            ),
        ),
    ]
